version: 2.1

orbs:
  slack: circleci/slack@3.4.2

jobs:
  lint:
    machine: true
    pre:
      - node node_modules/eslint/bin/eslint.js
    steps:
      - checkout
      - run: cd project
      - run: eslint 'src/**/*.js'

  deploy:
    machine: true
    steps:
      - checkout
      - run: ./deploy.sh
      - slack/status:
          fail_only: true
          mentions: 'r33d'

workflows:
  version: 2
  irreact-cicd:
    jobs:
      - lint
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - lint
