version: 2.1

orbs:
  slack: circleci/slack@3.4.2

jobs:
  lint:
    docker:
      - image: circleci/node:12.4
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install eslint
      - run: npm run lint

  deploy:
    machine: true
    steps:
      - checkout
      - run: ./deploy.sh
      - slack/status:
          fail_only: true
          mentions: 'r33d'

workflows:
  version: 2
  irreact-cicd:
    jobs:
      - lint
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - lint
